import { DistrictPreview } from './district-auto-complete.component';

export const districtPreviews: DistrictPreview[] = [
  { code: 1001, name: 'Flensburg', type: 'Kreisfreie Stadt' },
  { code: 1002, name: 'Kiel', type: 'Kreisfreie Stadt' },
  { code: 1003, name: 'Lübeck', type: 'Kreisfreie Stadt' },
  { code: 1004, name: 'Neumünster', type: 'Kreisfreie Stadt' },
  { code: 1051, name: 'Dithmarschen', type: 'Kreis' },
  { code: 1053, name: 'Herzogtum Lauenburg', type: 'Kreis' },
  { code: 1054, name: 'Nordfriesland', type: 'Kreis' },
  { code: 1055, name: 'Ostholstein', type: 'Kreis' },
  { code: 1056, name: 'Pinneberg', type: 'Kreis' },
  { code: 1057, name: 'Plön', type: 'Kreis' },
  { code: 1058, name: 'Rendsburg-Eckernförde', type: 'Kreis' },
  { code: 1059, name: 'Schleswig-Flensburg', type: 'Kreis' },
  { code: 1060, name: 'Segeberg', type: 'Kreis' },
  { code: 1061, name: 'Steinburg', type: 'Kreis' },
  { code: 1062, name: 'Stormarn', type: 'Kreis' },
  { code: 2000, name: 'Hamburg', type: 'Kreisfreie Stadt' },
  { code: 3101, name: 'Braunschweig', type: 'Kreisfreie Stadt' },
  { code: 3102, name: 'Salzgitter', type: 'Kreisfreie Stadt' },
  { code: 3103, name: 'Wolfsburg', type: 'Kreisfreie Stadt' },
  { code: 3151, name: 'Gifhorn', type: 'Landkreis' },
  { code: 3153, name: 'Goslar', type: 'Landkreis' },
  { code: 3154, name: 'Helmstedt', type: 'Landkreis' },
  { code: 3155, name: 'Northeim', type: 'Landkreis' },
  { code: 3157, name: 'Peine', type: 'Landkreis' },
  { code: 3158, name: 'Wolfenbüttel', type: 'Landkreis' },
  { code: 3159, name: 'Göttingen', type: 'Landkreis' },
  { code: 3241, name: 'Region Hannover', type: 'Landkreis' },
  { code: 3251, name: 'Diepholz', type: 'Landkreis' },
  { code: 3252, name: 'Hameln-Pyrmont', type: 'Landkreis' },
  { code: 3254, name: 'Hildesheim', type: 'Landkreis' },
  { code: 3255, name: 'Holzminden', type: 'Landkreis' },
  { code: 3256, name: 'Nienburg (Weser)', type: 'Landkreis' },
  { code: 3257, name: 'Schaumburg', type: 'Landkreis' },
  { code: 3351, name: 'Celle', type: 'Landkreis' },
  { code: 3352, name: 'Cuxhaven', type: 'Landkreis' },
  { code: 3353, name: 'Harburg', type: 'Landkreis' },
  { code: 3354, name: 'Lüchow-Dannenberg', type: 'Landkreis' },
  { code: 3355, name: 'Lüneburg', type: 'Landkreis' },
  { code: 3356, name: 'Osterholz', type: 'Landkreis' },
  { code: 3357, name: 'Rotenburg (Wümme)', type: 'Landkreis' },
  { code: 3358, name: 'Heidekreis', type: 'Landkreis' },
  { code: 3359, name: 'Stade', type: 'Landkreis' },
  { code: 3360, name: 'Uelzen', type: 'Landkreis' },
  { code: 3361, name: 'Verden', type: 'Landkreis' },
  { code: 3401, name: 'Delmenhorst', type: 'Kreisfreie Stadt' },
  { code: 3402, name: 'Emden', type: 'Kreisfreie Stadt' },
  { code: 3403, name: 'Oldenburg (Oldb)', type: 'Kreisfreie Stadt' },
  { code: 3404, name: 'Osnabrück', type: 'Kreisfreie Stadt' },
  { code: 3405, name: 'Wilhelmshaven', type: 'Kreisfreie Stadt' },
  { code: 3451, name: 'Ammerland', type: 'Landkreis' },
  { code: 3452, name: 'Aurich', type: 'Landkreis' },
  { code: 3453, name: 'Cloppenburg', type: 'Landkreis' },
  { code: 3454, name: 'Emsland', type: 'Landkreis' },
  { code: 3455, name: 'Friesland', type: 'Landkreis' },
  { code: 3456, name: 'Grafschaft Bentheim', type: 'Landkreis' },
  { code: 3457, name: 'Leer', type: 'Landkreis' },
  { code: 3458, name: 'Oldenburg', type: 'Landkreis' },
  { code: 3459, name: 'Osnabrück', type: 'Landkreis' },
  { code: 3460, name: 'Vechta', type: 'Landkreis' },
  { code: 3461, name: 'Wesermarsch', type: 'Landkreis' },
  { code: 3462, name: 'Wittmund', type: 'Landkreis' },
  { code: 4011, name: 'Bremen', type: 'Kreisfreie Stadt' },
  { code: 4012, name: 'Bremerhaven', type: 'Kreisfreie Stadt' },
  { code: 5111, name: 'Düsseldorf', type: 'Kreisfreie Stadt' },
  { code: 5112, name: 'Duisburg', type: 'Kreisfreie Stadt' },
  { code: 5113, name: 'Essen', type: 'Kreisfreie Stadt' },
  { code: 5114, name: 'Krefeld', type: 'Kreisfreie Stadt' },
  { code: 5116, name: 'Mönchengladbach', type: 'Kreisfreie Stadt' },
  { code: 5117, name: 'Mülheim an der Ruhr', type: 'Kreisfreie Stadt' },
  { code: 5119, name: 'Oberhausen', type: 'Kreisfreie Stadt' },
  { code: 5120, name: 'Remscheid', type: 'Kreisfreie Stadt' },
  { code: 5122, name: 'Solingen', type: 'Kreisfreie Stadt' },
  { code: 5124, name: 'Wuppertal', type: 'Kreisfreie Stadt' },
  { code: 5154, name: 'Kleve', type: 'Kreis' },
  { code: 5158, name: 'Mettmann', type: 'Kreis' },
  { code: 5162, name: 'Rhein-Kreis Neuss', type: 'Kreis' },
  { code: 5166, name: 'Viersen', type: 'Kreis' },
  { code: 5170, name: 'Wesel', type: 'Kreis' },
  { code: 5314, name: 'Bonn', type: 'Kreisfreie Stadt' },
  { code: 5315, name: 'Köln', type: 'Kreisfreie Stadt' },
  { code: 5316, name: 'Leverkusen', type: 'Kreisfreie Stadt' },
  { code: 5334, name: 'Städteregion Aachen', type: 'Kreis' },
  { code: 5358, name: 'Düren', type: 'Kreis' },
  { code: 5362, name: 'Rhein-Erft-Kreis', type: 'Kreis' },
  { code: 5366, name: 'Euskirchen', type: 'Kreis' },
  { code: 5370, name: 'Heinsberg', type: 'Kreis' },
  { code: 5374, name: 'Oberbergischer Kreis', type: 'Kreis' },
  { code: 5378, name: 'Rheinisch-Bergischer Kreis', type: 'Kreis' },
  { code: 5382, name: 'Rhein-Sieg-Kreis', type: 'Kreis' },
  { code: 5512, name: 'Bottrop', type: 'Kreisfreie Stadt' },
  { code: 5513, name: 'Gelsenkirchen', type: 'Kreisfreie Stadt' },
  { code: 5515, name: 'Münster', type: 'Kreisfreie Stadt' },
  { code: 5554, name: 'Borken', type: 'Kreis' },
  { code: 5558, name: 'Coesfeld', type: 'Kreis' },
  { code: 5562, name: 'Recklinghausen', type: 'Kreis' },
  { code: 5566, name: 'Steinfurt', type: 'Kreis' },
  { code: 5570, name: 'Warendorf', type: 'Kreis' },
  { code: 5711, name: 'Bielefeld', type: 'Kreisfreie Stadt' },
  { code: 5754, name: 'Gütersloh', type: 'Kreis' },
  { code: 5758, name: 'Herford', type: 'Kreis' },
  { code: 5762, name: 'Höxter', type: 'Kreis' },
  { code: 5766, name: 'Lippe', type: 'Kreis' },
  { code: 5770, name: 'Minden-Lübbecke', type: 'Kreis' },
  { code: 5774, name: 'Paderborn', type: 'Kreis' },
  { code: 5911, name: 'Bochum', type: 'Kreisfreie Stadt' },
  { code: 5913, name: 'Dortmund', type: 'Kreisfreie Stadt' },
  { code: 5914, name: 'Hagen', type: 'Kreisfreie Stadt' },
  { code: 5915, name: 'Hamm', type: 'Kreisfreie Stadt' },
  { code: 5916, name: 'Herne', type: 'Kreisfreie Stadt' },
  { code: 5954, name: 'Ennepe-Ruhr-Kreis', type: 'Kreis' },
  { code: 5958, name: 'Hochsauerlandkreis', type: 'Kreis' },
  { code: 5962, name: 'Märkischer Kreis', type: 'Kreis' },
  { code: 5966, name: 'Olpe', type: 'Kreis' },
  { code: 5970, name: 'Siegen-Wittgenstein', type: 'Kreis' },
  { code: 5974, name: 'Soest', type: 'Kreis' },
  { code: 5978, name: 'Unna', type: 'Kreis' },
  { code: 6411, name: 'Darmstadt', type: 'Kreisfreie Stadt' },
  { code: 6412, name: 'Frankfurt am Main', type: 'Kreisfreie Stadt' },
  { code: 6413, name: 'Offenbach am Main', type: 'Kreisfreie Stadt' },
  { code: 6414, name: 'Wiesbaden', type: 'Kreisfreie Stadt' },
  { code: 6431, name: 'Bergstraße', type: 'Landkreis' },
  { code: 6432, name: 'Darmstadt-Dieburg', type: 'Landkreis' },
  { code: 6433, name: 'Groß-Gerau', type: 'Landkreis' },
  { code: 6434, name: 'Hochtaunuskreis', type: 'Landkreis' },
  { code: 6435, name: 'Main-Kinzig-Kreis', type: 'Landkreis' },
  { code: 6436, name: 'Main-Taunus-Kreis', type: 'Landkreis' },
  { code: 6437, name: 'Odenwaldkreis', type: 'Landkreis' },
  { code: 6438, name: 'Offenbach', type: 'Landkreis' },
  { code: 6439, name: 'Rheingau-Taunus-Kreis', type: 'Landkreis' },
  { code: 6440, name: 'Wetteraukreis', type: 'Landkreis' },
  { code: 6531, name: 'Gießen', type: 'Landkreis' },
  { code: 6532, name: 'Lahn-Dill-Kreis', type: 'Landkreis' },
  { code: 6533, name: 'Limburg-Weilburg', type: 'Landkreis' },
  { code: 6534, name: 'Marburg-Biedenkopf', type: 'Landkreis' },
  { code: 6535, name: 'Vogelsbergkreis', type: 'Landkreis' },
  { code: 6611, name: 'Kassel', type: 'Kreisfreie Stadt' },
  { code: 6631, name: 'Fulda', type: 'Landkreis' },
  { code: 6632, name: 'Hersfeld-Rotenburg', type: 'Landkreis' },
  { code: 6633, name: 'Kassel', type: 'Landkreis' },
  { code: 6634, name: 'Schwalm-Eder-Kreis', type: 'Landkreis' },
  { code: 6635, name: 'Waldeck-Frankenberg', type: 'Landkreis' },
  { code: 6636, name: 'Werra-Meißner-Kreis', type: 'Landkreis' },
  { code: 7111, name: 'Koblenz', type: 'Kreisfreie Stadt' },
  { code: 7131, name: 'Ahrweiler', type: 'Landkreis' },
  { code: 7132, name: 'Altenkirchen (Westerwald)', type: 'Landkreis' },
  { code: 7133, name: 'Bad Kreuznach', type: 'Landkreis' },
  { code: 7134, name: 'Birkenfeld', type: 'Landkreis' },
  { code: 7135, name: 'Cochem-Zell', type: 'Landkreis' },
  { code: 7137, name: 'Mayen-Koblenz', type: 'Landkreis' },
  { code: 7138, name: 'Neuwied', type: 'Landkreis' },
  { code: 7140, name: 'Rhein-Hunsrück-Kreis', type: 'Landkreis' },
  { code: 7141, name: 'Rhein-Lahn-Kreis', type: 'Landkreis' },
  { code: 7143, name: 'Westerwaldkreis', type: 'Landkreis' },
  { code: 7211, name: 'Trier', type: 'Kreisfreie Stadt' },
  { code: 7231, name: 'Bernkastel-Wittlich', type: 'Landkreis' },
  { code: 7232, name: 'Eifelkreis Bitburg-Prüm', type: 'Landkreis' },
  { code: 7233, name: 'Vulkaneifel', type: 'Landkreis' },
  { code: 7235, name: 'Trier-Saarburg', type: 'Landkreis' },
  { code: 7311, name: 'Frankenthal (Pfalz)', type: 'Kreisfreie Stadt' },
  { code: 7312, name: 'Kaiserslautern', type: 'Kreisfreie Stadt' },
  { code: 7313, name: 'Landau in der Pfalz', type: 'Kreisfreie Stadt' },
  { code: 7314, name: 'Ludwigshafen am Rhein', type: 'Kreisfreie Stadt' },
  { code: 7315, name: 'Mainz', type: 'Kreisfreie Stadt' },
  { code: 7316, name: 'Neustadt an der Weinstraße', type: 'Kreisfreie Stadt' },
  { code: 7317, name: 'Pirmasens', type: 'Kreisfreie Stadt' },
  { code: 7318, name: 'Speyer', type: 'Kreisfreie Stadt' },
  { code: 7319, name: 'Worms', type: 'Kreisfreie Stadt' },
  { code: 7320, name: 'Zweibrücken', type: 'Kreisfreie Stadt' },
  { code: 7331, name: 'Alzey-Worms', type: 'Landkreis' },
  { code: 7332, name: 'Bad Dürkheim', type: 'Landkreis' },
  { code: 7333, name: 'Donnersbergkreis', type: 'Landkreis' },
  { code: 7334, name: 'Germersheim', type: 'Landkreis' },
  { code: 7335, name: 'Kaiserslautern', type: 'Landkreis' },
  { code: 7336, name: 'Kusel', type: 'Landkreis' },
  { code: 7337, name: 'Südliche Weinstraße', type: 'Landkreis' },
  { code: 7338, name: 'Rhein-Pfalz-Kreis', type: 'Landkreis' },
  { code: 7339, name: 'Mainz-Bingen', type: 'Landkreis' },
  { code: 7340, name: 'Südwestpfalz', type: 'Landkreis' },
  { code: 8111, name: 'Stuttgart', type: 'Stadtkreis' },
  { code: 8115, name: 'Böblingen', type: 'Landkreis' },
  { code: 8116, name: 'Esslingen', type: 'Landkreis' },
  { code: 8117, name: 'Göppingen', type: 'Landkreis' },
  { code: 8118, name: 'Ludwigsburg', type: 'Landkreis' },
  { code: 8119, name: 'Rems-Murr-Kreis', type: 'Landkreis' },
  { code: 8121, name: 'Heilbronn', type: 'Stadtkreis' },
  { code: 8125, name: 'Heilbronn', type: 'Landkreis' },
  { code: 8126, name: 'Hohenlohekreis', type: 'Landkreis' },
  { code: 8127, name: 'Schwäbisch Hall', type: 'Landkreis' },
  { code: 8128, name: 'Main-Tauber-Kreis', type: 'Landkreis' },
  { code: 8135, name: 'Heidenheim', type: 'Landkreis' },
  { code: 8136, name: 'Ostalbkreis', type: 'Landkreis' },
  { code: 8211, name: 'Baden-Baden', type: 'Stadtkreis' },
  { code: 8212, name: 'Karlsruhe', type: 'Stadtkreis' },
  { code: 8215, name: 'Karlsruhe', type: 'Landkreis' },
  { code: 8216, name: 'Rastatt', type: 'Landkreis' },
  { code: 8221, name: 'Heidelberg', type: 'Stadtkreis' },
  { code: 8222, name: 'Mannheim', type: 'Stadtkreis' },
  { code: 8225, name: 'Neckar-Odenwald-Kreis', type: 'Landkreis' },
  { code: 8226, name: 'Rhein-Neckar-Kreis', type: 'Landkreis' },
  { code: 8231, name: 'Pforzheim', type: 'Stadtkreis' },
  { code: 8235, name: 'Calw', type: 'Landkreis' },
  { code: 8236, name: 'Enzkreis', type: 'Landkreis' },
  { code: 8237, name: 'Freudenstadt', type: 'Landkreis' },
  { code: 8311, name: 'Freiburg im Breisgau', type: 'Stadtkreis' },
  { code: 8315, name: 'Breisgau-Hochschwarzwald', type: 'Landkreis' },
  { code: 8316, name: 'Emmendingen', type: 'Landkreis' },
  { code: 8317, name: 'Ortenaukreis', type: 'Landkreis' },
  { code: 8325, name: 'Rottweil', type: 'Landkreis' },
  { code: 8326, name: 'Schwarzwald-Baar-Kreis', type: 'Landkreis' },
  { code: 8327, name: 'Tuttlingen', type: 'Landkreis' },
  { code: 8335, name: 'Konstanz', type: 'Landkreis' },
  { code: 8336, name: 'Lörrach', type: 'Landkreis' },
  { code: 8337, name: 'Waldshut', type: 'Landkreis' },
  { code: 8415, name: 'Reutlingen', type: 'Landkreis' },
  { code: 8416, name: 'Tübingen', type: 'Landkreis' },
  { code: 8417, name: 'Zollernalbkreis', type: 'Landkreis' },
  { code: 8421, name: 'Ulm', type: 'Stadtkreis' },
  { code: 8425, name: 'Alb-Donau-Kreis', type: 'Landkreis' },
  { code: 8426, name: 'Biberach', type: 'Landkreis' },
  { code: 8435, name: 'Bodenseekreis', type: 'Landkreis' },
  { code: 8436, name: 'Ravensburg', type: 'Landkreis' },
  { code: 8437, name: 'Sigmaringen', type: 'Landkreis' },
  { code: 9161, name: 'Ingolstadt', type: 'Kreisfreie Stadt' },
  { code: 9162, name: 'München', type: 'Kreisfreie Stadt' },
  { code: 9163, name: 'Rosenheim', type: 'Kreisfreie Stadt' },
  { code: 9171, name: 'Altötting', type: 'Landkreis' },
  { code: 9172, name: 'Berchtesgadener Land', type: 'Landkreis' },
  { code: 9173, name: 'Bad Tölz-Wolfratshausen', type: 'Landkreis' },
  { code: 9174, name: 'Dachau', type: 'Landkreis' },
  { code: 9175, name: 'Ebersberg', type: 'Landkreis' },
  { code: 9176, name: 'Eichstätt', type: 'Landkreis' },
  { code: 9177, name: 'Erding', type: 'Landkreis' },
  { code: 9178, name: 'Freising', type: 'Landkreis' },
  { code: 9179, name: 'Fürstenfeldbruck', type: 'Landkreis' },
  { code: 9180, name: 'Garmisch-Partenkirchen', type: 'Landkreis' },
  { code: 9181, name: 'Landsberg am Lech', type: 'Landkreis' },
  { code: 9182, name: 'Miesbach', type: 'Landkreis' },
  { code: 9183, name: 'Mühldorf a. Inn', type: 'Landkreis' },
  { code: 9184, name: 'München', type: 'Landkreis' },
  { code: 9185, name: 'Neuburg-Schrobenhausen', type: 'Landkreis' },
  { code: 9186, name: 'Pfaffenhofen a.d. Ilm', type: 'Landkreis' },
  { code: 9187, name: 'Rosenheim', type: 'Landkreis' },
  { code: 9188, name: 'Starnberg', type: 'Landkreis' },
  { code: 9189, name: 'Traunstein', type: 'Landkreis' },
  { code: 9190, name: 'Weilheim-Schongau', type: 'Landkreis' },
  { code: 9261, name: 'Landshut', type: 'Kreisfreie Stadt' },
  { code: 9262, name: 'Passau', type: 'Kreisfreie Stadt' },
  { code: 9263, name: 'Straubing', type: 'Kreisfreie Stadt' },
  { code: 9271, name: 'Deggendorf', type: 'Landkreis' },
  { code: 9272, name: 'Freyung-Grafenau', type: 'Landkreis' },
  { code: 9273, name: 'Kelheim', type: 'Landkreis' },
  { code: 9274, name: 'Landshut', type: 'Landkreis' },
  { code: 9275, name: 'Passau', type: 'Landkreis' },
  { code: 9276, name: 'Regen', type: 'Landkreis' },
  { code: 9277, name: 'Rottal-Inn', type: 'Landkreis' },
  { code: 9278, name: 'Straubing-Bogen', type: 'Landkreis' },
  { code: 9279, name: 'Dingolfing-Landau', type: 'Landkreis' },
  { code: 9361, name: 'Amberg', type: 'Kreisfreie Stadt' },
  { code: 9362, name: 'Regensburg', type: 'Kreisfreie Stadt' },
  { code: 9363, name: 'Weiden i.d. OPf.', type: 'Kreisfreie Stadt' },
  { code: 9371, name: 'Amberg-Sulzbach', type: 'Landkreis' },
  { code: 9372, name: 'Cham', type: 'Landkreis' },
  { code: 9373, name: 'Neumarkt i.d. OPf.', type: 'Landkreis' },
  { code: 9374, name: 'Neustadt a.d. Waldnaab', type: 'Landkreis' },
  { code: 9375, name: 'Regensburg', type: 'Landkreis' },
  { code: 9376, name: 'Schwandorf', type: 'Landkreis' },
  { code: 9377, name: 'Tirschenreuth', type: 'Landkreis' },
  { code: 9461, name: 'Bamberg', type: 'Kreisfreie Stadt' },
  { code: 9462, name: 'Bayreuth', type: 'Kreisfreie Stadt' },
  { code: 9463, name: 'Coburg', type: 'Kreisfreie Stadt' },
  { code: 9464, name: 'Hof', type: 'Kreisfreie Stadt' },
  { code: 9471, name: 'Bamberg', type: 'Landkreis' },
  { code: 9472, name: 'Bayreuth', type: 'Landkreis' },
  { code: 9473, name: 'Coburg', type: 'Landkreis' },
  { code: 9474, name: 'Forchheim', type: 'Landkreis' },
  { code: 9475, name: 'Hof', type: 'Landkreis' },
  { code: 9476, name: 'Kronach', type: 'Landkreis' },
  { code: 9477, name: 'Kulmbach', type: 'Landkreis' },
  { code: 9478, name: 'Lichtenfels', type: 'Landkreis' },
  { code: 9479, name: 'Wunsiedel i. Fichtelgebirge', type: 'Landkreis' },
  { code: 9561, name: 'Ansbach', type: 'Kreisfreie Stadt' },
  { code: 9562, name: 'Erlangen', type: 'Kreisfreie Stadt' },
  { code: 9563, name: 'Fürth', type: 'Kreisfreie Stadt' },
  { code: 9564, name: 'Nürnberg', type: 'Kreisfreie Stadt' },
  { code: 9565, name: 'Schwabach', type: 'Kreisfreie Stadt' },
  { code: 9571, name: 'Ansbach', type: 'Landkreis' },
  { code: 9572, name: 'Erlangen-Höchstadt', type: 'Landkreis' },
  { code: 9573, name: 'Fürth', type: 'Landkreis' },
  { code: 9574, name: 'Nürnberger Land', type: 'Landkreis' },
  { code: 9575, name: 'Neustadt a.d. Aisch-Bad Windsheim', type: 'Landkreis' },
  { code: 9576, name: 'Roth', type: 'Landkreis' },
  { code: 9577, name: 'Weißenburg-Gunzenhausen', type: 'Landkreis' },
  { code: 9661, name: 'Aschaffenburg', type: 'Kreisfreie Stadt' },
  { code: 9662, name: 'Schweinfurt', type: 'Kreisfreie Stadt' },
  { code: 9663, name: 'Würzburg', type: 'Kreisfreie Stadt' },
  { code: 9671, name: 'Aschaffenburg', type: 'Landkreis' },
  { code: 9672, name: 'Bad Kissingen', type: 'Landkreis' },
  { code: 9673, name: 'Rhön-Grabfeld', type: 'Landkreis' },
  { code: 9674, name: 'Haßberge', type: 'Landkreis' },
  { code: 9675, name: 'Kitzingen', type: 'Landkreis' },
  { code: 9676, name: 'Miltenberg', type: 'Landkreis' },
  { code: 9677, name: 'Main-Spessart', type: 'Landkreis' },
  { code: 9678, name: 'Schweinfurt', type: 'Landkreis' },
  { code: 9679, name: 'Würzburg', type: 'Landkreis' },
  { code: 9761, name: 'Augsburg', type: 'Kreisfreie Stadt' },
  { code: 9762, name: 'Kaufbeuren', type: 'Kreisfreie Stadt' },
  { code: 9763, name: 'Kempten (Allgäu)', type: 'Kreisfreie Stadt' },
  { code: 9764, name: 'Memmingen', type: 'Kreisfreie Stadt' },
  { code: 9771, name: 'Aichach-Friedberg', type: 'Landkreis' },
  { code: 9772, name: 'Augsburg', type: 'Landkreis' },
  { code: 9773, name: 'Dillingen a.d. Donau', type: 'Landkreis' },
  { code: 9774, name: 'Günzburg', type: 'Landkreis' },
  { code: 9775, name: 'Neu-Ulm', type: 'Landkreis' },
  { code: 9776, name: 'Lindau (Bodensee)', type: 'Landkreis' },
  { code: 9777, name: 'Ostallgäu', type: 'Landkreis' },
  { code: 9778, name: 'Unterallgäu', type: 'Landkreis' },
  { code: 9779, name: 'Donau-Ries', type: 'Landkreis' },
  { code: 9780, name: 'Oberallgäu', type: 'Landkreis' },
  { code: 10041, name: 'Regionalverband Saarbrücken', type: 'Landkreis' },
  { code: 10042, name: 'Merzig-Wadern', type: 'Landkreis' },
  { code: 10043, name: 'Neunkirchen', type: 'Landkreis' },
  { code: 10044, name: 'Saarlouis', type: 'Landkreis' },
  { code: 10045, name: 'Saarpfalz-Kreis', type: 'Landkreis' },
  { code: 10046, name: 'St. Wendel', type: 'Landkreis' },
  { code: 12051, name: 'Brandenburg an der Havel', type: 'Kreisfreie Stadt' },
  { code: 12052, name: 'Cottbus', type: 'Kreisfreie Stadt' },
  { code: 12053, name: 'Frankfurt (Oder)', type: 'Kreisfreie Stadt' },
  { code: 12054, name: 'Potsdam', type: 'Kreisfreie Stadt' },
  { code: 12060, name: 'Barnim', type: 'Landkreis' },
  { code: 12061, name: 'Dahme-Spreewald', type: 'Landkreis' },
  { code: 12062, name: 'Elbe-Elster', type: 'Landkreis' },
  { code: 12063, name: 'Havelland', type: 'Landkreis' },
  { code: 12064, name: 'Märkisch-Oderland', type: 'Landkreis' },
  { code: 12065, name: 'Oberhavel', type: 'Landkreis' },
  { code: 12066, name: 'Oberspreewald-Lausitz', type: 'Landkreis' },
  { code: 12067, name: 'Oder-Spree', type: 'Landkreis' },
  { code: 12068, name: 'Ostprignitz-Ruppin', type: 'Landkreis' },
  { code: 12069, name: 'Potsdam-Mittelmark', type: 'Landkreis' },
  { code: 12070, name: 'Prignitz', type: 'Landkreis' },
  { code: 12071, name: 'Spree-Neiße', type: 'Landkreis' },
  { code: 12072, name: 'Teltow-Fläming', type: 'Landkreis' },
  { code: 12073, name: 'Uckermark', type: 'Landkreis' },
  { code: 13003, name: 'Rostock', type: 'Kreisfreie Stadt' },
  { code: 13004, name: 'Schwerin', type: 'Kreisfreie Stadt' },
  { code: 13071, name: 'Mecklenburgische Seenplatte', type: 'Landkreis' },
  { code: 13072, name: 'Rostock', type: 'Landkreis' },
  { code: 13073, name: 'Vorpommern-Rügen', type: 'Landkreis' },
  { code: 13074, name: 'Nordwestmecklenburg', type: 'Landkreis' },
  { code: 13075, name: 'Vorpommern-Greifswald', type: 'Landkreis' },
  { code: 13076, name: 'Ludwigslust-Parchim', type: 'Landkreis' },
  { code: 14511, name: 'Chemnitz', type: 'Kreisfreie Stadt' },
  { code: 14521, name: 'Erzgebirgskreis', type: 'Landkreis' },
  { code: 14522, name: 'Mittelsachsen', type: 'Landkreis' },
  { code: 14523, name: 'Vogtlandkreis', type: 'Landkreis' },
  { code: 14524, name: 'Zwickau', type: 'Landkreis' },
  { code: 14612, name: 'Dresden', type: 'Kreisfreie Stadt' },
  { code: 14625, name: 'Bautzen', type: 'Landkreis' },
  { code: 14626, name: 'Görlitz', type: 'Landkreis' },
  { code: 14627, name: 'Meißen', type: 'Landkreis' },
  { code: 14628, name: 'Sächsische Schweiz-Osterzgebirge', type: 'Landkreis' },
  { code: 14713, name: 'Leipzig', type: 'Kreisfreie Stadt' },
  { code: 14729, name: 'Leipzig', type: 'Landkreis' },
  { code: 14730, name: 'Nordsachsen', type: 'Landkreis' },
  { code: 15001, name: 'Dessau-Roßlau', type: 'Kreisfreie Stadt' },
  { code: 15002, name: 'Halle (Saale)', type: 'Kreisfreie Stadt' },
  { code: 15003, name: 'Magdeburg', type: 'Kreisfreie Stadt' },
  { code: 15081, name: 'Altmarkkreis Salzwedel', type: 'Landkreis' },
  { code: 15082, name: 'Anhalt-Bitterfeld', type: 'Landkreis' },
  { code: 15083, name: 'Börde', type: 'Landkreis' },
  { code: 15084, name: 'Burgenlandkreis', type: 'Landkreis' },
  { code: 15085, name: 'Harz', type: 'Landkreis' },
  { code: 15086, name: 'Jerichower Land', type: 'Landkreis' },
  { code: 15087, name: 'Mansfeld-Südharz', type: 'Landkreis' },
  { code: 15088, name: 'Saalekreis', type: 'Landkreis' },
  { code: 15089, name: 'Salzlandkreis', type: 'Landkreis' },
  { code: 15090, name: 'Stendal', type: 'Landkreis' },
  { code: 15091, name: 'Wittenberg', type: 'Landkreis' },
  { code: 16051, name: 'Erfurt', type: 'Kreisfreie Stadt' },
  { code: 16052, name: 'Gera', type: 'Kreisfreie Stadt' },
  { code: 16053, name: 'Jena', type: 'Kreisfreie Stadt' },
  { code: 16054, name: 'Suhl', type: 'Kreisfreie Stadt' },
  { code: 16055, name: 'Weimar', type: 'Kreisfreie Stadt' },
  { code: 16061, name: 'Eichsfeld', type: 'Landkreis' },
  { code: 16062, name: 'Nordhausen', type: 'Landkreis' },
  { code: 16063, name: 'Wartburgkreis', type: 'Landkreis' },
  { code: 16064, name: 'Unstrut-Hainich-Kreis', type: 'Landkreis' },
  { code: 16065, name: 'Kyffhäuserkreis', type: 'Landkreis' },
  { code: 16066, name: 'Schmalkalden-Meiningen', type: 'Landkreis' },
  { code: 16067, name: 'Gotha', type: 'Landkreis' },
  { code: 16068, name: 'Sömmerda', type: 'Landkreis' },
  { code: 16069, name: 'Hildburghausen', type: 'Landkreis' },
  { code: 16070, name: 'Ilm-Kreis', type: 'Landkreis' },
  { code: 16071, name: 'Weimarer Land', type: 'Landkreis' },
  { code: 16072, name: 'Sonneberg', type: 'Landkreis' },
  { code: 16073, name: 'Saalfeld-Rudolstadt', type: 'Landkreis' },
  { code: 16074, name: 'Saale-Holzland-Kreis', type: 'Landkreis' },
  { code: 16075, name: 'Saale-Orla-Kreis', type: 'Landkreis' },
  { code: 16076, name: 'Greiz', type: 'Landkreis' },
  { code: 16077, name: 'Altenburger Land', type: 'Landkreis' },
  { code: 11012, name: 'Berlin Reinickendorf', type: 'Bezirk' },
  { code: 11004, name: 'Berlin Charlottenburg-Wilmersdorf', type: 'Bezirk' },
  { code: 11009, name: 'Berlin Treptow-Köpenick', type: 'Bezirk' },
  { code: 11003, name: 'Berlin Pankow', type: 'Bezirk' },
  { code: 11008, name: 'Berlin Neukölln', type: 'Bezirk' },
  { code: 11011, name: 'Berlin Lichtenberg', type: 'Bezirk' },
  { code: 11010, name: 'Berlin Marzahn-Hellersdorf', type: 'Bezirk' },
  { code: 11005, name: 'Berlin Spandau', type: 'Bezirk' },
  { code: 11006, name: 'Berlin Steglitz-Zehlendorf', type: 'Bezirk' },
  { code: 11001, name: 'Berlin Mitte', type: 'Bezirk' },
  { code: 11002, name: 'Berlin Friedrichshain-Kreuzberg', type: 'Bezirk' },
  { code: 11007, name: 'Berlin Tempelhof-Schöneberg', type: 'Bezirk' },
];
